# Generated by Django 3.2.3 on 2021-06-15 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('MobileNo', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Gender', models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='', null=True)),
                ('DateOfBirth', models.DateField(null=True)),
                ('ProfilePicURL', models.ImageField(blank=True, null=True, upload_to='documents')),
                ('DateCreated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('IsActive', models.BooleanField(null=True)),
            ],
        ),
    ]
