# Generated by Django 3.2.3 on 2021-06-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('MobileNo', models.BigIntegerField(max_length=10)),
                ('Password', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
            ],
        ),
    ]
