# Generated by Django 3.2.3 on 2021-06-18 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shouts',
            fields=[
                ('ShoutsId', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('TextContent', models.TextField(max_length=400)),
                ('File', models.FileField(blank=True, upload_to='media/imgs')),
                ('IsDeleted', models.BooleanField(default=False, null=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='ReportedShouts',
            fields=[
                ('ReportId', models.AutoField(primary_key=True, serialize=False)),
                ('ReportedDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('IsDeleted', models.BooleanField(default=False, null=True)),
                ('ShoutsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.shouts')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusCode', models.IntegerField(choices=[(0, 'pending'), (1, 'Accepted'), (2, 'Declined'), (3, 'Blocked'), (4, 'Unfriend')], default=4)),
                ('DateCreated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ActionUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionUser_id', to='UserApp.users')),
                ('FriendId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_id', to='UserApp.users')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='UserApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('CommentId', models.AutoField(primary_key=True, serialize=False)),
                ('CommentContent', models.TextField(max_length=200)),
                ('DateCreated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ShoutsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.shouts')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.users')),
            ],
        ),
    ]
