# Generated by Django 3.2.3 on 2021-06-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_users_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
