# Generated by Django 3.2.3 on 2021-06-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_comments_friends_reportedshouts_shouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouts',
            name='FileType',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shouts',
            name='File',
            field=models.CharField(max_length=400),
        ),
    ]
